project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - photos.qmd
      - projects.qmd
      - Coursework.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

